### ISSUE TITLE
Can't play audio

### ISSUE THREAD

**Issue by Keerthi-Sparkout** [dimitris-c/AudioStreaming#25]
I got this error while playing an audio. This audio recorded from samsung mobile.
"Couldn't parse the bytes from the stream. Status: The file is malformed, not a valid instance of an audio file of its type, or not recognized as an audio file."

Note: But this same audio is playing well in avplayer and safari browser also.

**Comment by dimitris-c** [comment]
This is probably due to an invalid file — error code `kAudioFileStreamError_InvalidFile`
This library is using Audio File Stream Services — https://developer.apple.com/documentation/audiotoolbox/audio_file_stream_services?changes=__11&language=swift

I'm not 100% how AVAudio solves this, if you can share the audio file I can investigate if I have some time

**Comment by dimitris-c** [comment]
Closing this, due to lack of response.

**Comment by dimitris-c** [comment]
@PriyankGandhi30 I can't access the URL, make sure you're using the correct authentication, you can pass headers if required
