### ISSUE TITLE
can't play non-optimized remote M4A

### ISSUE THREAD

**Issue by vegetalu** [dimitris-c/AudioStreaming#76]
https://mcdn.podbean.com/mf/web/khh8azvsc8bedf9a/Boomers_Know_Stuff_Part_1_2378b1ju.m4a
can't play this file with v1.2.0

**Comment by dimitris-c** [comment]
Thanks for raising this, will have a look

**Comment by dimitris-c** [comment]
There's seems to be an issue with this audio file and `AudioFileStreamParseBytes` doesn't produce `kAudioFileStreamProperty_ReadyToProducePackets` which is required to be called  by `Audio File Stream Services` in order to start play the audio packets. What's interesting it's that doesn't even work when running ffmpeg's qt-faststart (which optimises the audio file). We've hit a dead end as this would require to provide our own decoding mechanism which is out of scope for this library.
